# PSTAT100 Data Science Concepts and Analysis
## FINAL PROJECT

**Author:CHLOE LO PAPA**
**Date:**

---

## 1. Introduction

In this project we will be exploring global patterns are associated with countries that have low access to electricity using a data set made available by [Electrification Dataset, World Bank Group](https://data.worldbank.org/indicator/EG.ELC.ACCS.ZS?locations=1W&start=1990&end=2023&view=chart). This data was last updated in 2023.

Throughout this assignment we will:

1. Review data documentation to:
   1. Identify population, sampling frame, sample.
   2. Assess scope of inference.
2. Prepare data by:
   1. Importing data.
   2. Manipulating `pandas` data frames.
   3. Merging data frames.
3. Performing exploratory data analysis by:
   1. Producing scatter plots.
   2. Multiplots.
   3. Univariate and multivariate analysis.
   4. Aggregation and tabulation.
   5. Visualizing trends.
4. Practice good communication by:
   1. Commenting on tables and figures.
   2. Summarizing results.
   3. Proposing hypotheses.

---

## 2. Background

Global access to electricity is a fundamental pillar of socioeconomic development and a core component of the United Nations Sustainable Development Goals (SDGs). Historically, electrification was viewed through a purely industrial lens, but contemporary research emphasizes its role as a "human right" essential for health, education, and poverty reduction. Despite its importance, universal access remains a long winded goal due to geographical barriers, political instability, and the high infrastructure costs associated with reaching remote rural populations.  

The Sustainable Development Goal 7 (SDG 7) initiative aims to ensure access to affordable, reliable, sustainable, and modern energy for all by 2030. To monitor progress toward this target, the World Bank and the Energy Sector Management Assistance Program (ESMAP) maintain a comprehensive global database on electrification rates.  

The SDG 7.1.1 Electrification Dataset provides standardized measures of the percentage of the population with access to electricity for over 200 countries and territories. This data is compiled from a variety of sources, including household surveys (such as the Demographic and Health Surveys) and census data. Global energy access observed from 1990 through 2023 shows a significant increase in global electrification, with the percentage of the population having access rising from roughly 71% in 1990 to over 91% by 2022, but also a persistent "rural-urban" gap, where urban areas maintain almost complete access while rural regions, continue to lag.

In this assignment we shall be making use of the following python libraries:

In [ ]:
# Libraries
import numpy as np
import pandas as pd
import missingno as msno
import matplotlib.pyplot as plt
import seaborn as sns

# Figure formatting
sns.set_style("whitegrid")
sns.set_palette("Set2")

---

## 3. Data Import

We begin by downloading the relevant data files:

1. `Metadata_Country_API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_127016.csv` - contains geographic information.
2. `API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_127016.csv` - contains the percent of electrification by year.

In [ ]:
# Load raw data
data_geo = pd.read_csv(
    "Metadata_Country_API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_127016.csv"
)
data_elec = pd.read_csv(
    "API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_127016.csv", skiprows=4
)

### 3.1 View Data

We start by looking at the `shape` of the data and printing the first few rows:

In [ ]:
# Print test data shape
print("Test data shape electrification:", data_elec.shape)

#remove unnamed empty column at end of dataset
data_elec = data_elec.loc[:, ~data_elec.columns.str.contains('^Unnamed')]
data_elec.head()

Test data shape electrification: (266, 71)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.900000,100.000000,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.801258,50.667516,NaN,NaN
2,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.700000,97.700000,93.400000,97.700000,97.700000,97.700000,85.300000,85.300000,NaN,NaN
3,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,51.045127,48.900728,51.335829,51.291577,51.856043,54.368599,55.686683,57.069267,NaN,NaN
4,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,41.800000,42.900000,45.300000,45.600000,47.000000,48.200000,48.500000,51.100000,NaN,NaN

In [ ]:
# Print test data shape
print("Test data geography:", data_elec.shape)

#remove unnamed empty column at end of dataset
data_elec = data_elec.loc[:, ~data_elec.columns.str.contains('^Unnamed')]
data_elec.head()

Test data geography: (266, 70)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.900000,100.000000,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.801258,50.667516,NaN,NaN
2,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.700000,97.700000,93.400000,97.700000,97.700000,97.700000,85.300000,85.300000,NaN,NaN
3,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,51.045127,48.900728,51.335829,51.291577,51.856043,54.368599,55.686683,57.069267,NaN,NaN
4,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,41.800000,42.900000,45.300000,45.600000,47.000000,48.200000,48.500000,51.100000,NaN,NaN

<div class="alert alert-block alert-info">
</div>

#### 1.1 Interpreting 2013 and 2023 Electrification



---

**Solution:**

In [ ]:
df_years_isolated = data_elec[['2013', '2023']]

print(df_years_isolated.head())

         2013        2023
0  100.000000  100.000000
1   31.723574   50.667516
2   68.000000   85.300000
3   47.194503   57.069267
4   38.400000   51.100000

### 1.2 Interpreting Income

In [ ]:
data_geo_isolated = data_geo[['Country Code', 'IncomeGroup']]

print(data_geo_isolated.head())

##Merge Datasets

In [ ]:
# Merge the datasets on 'Country Code'
df_merged = pd.merge(df_years_isolated, data_geo_isolated, on='Country Code', how='inner')

# Display the first few rows to verify
print(df_merged.head())

# Evaluating Missing Data

In [ ]:
import missingno as msno
import matplotlib.pyplot as plt

msno.matrix(df_merged)
plt.title("Missing Data Patterns")
plt.show()

df_merged.isnull().sum()

The missing data visualization shows that the dataset has most values for the variables, except for Income Group. The variables Country Code and Country Name contain no missing observations, while the electrification variables for 2013 and 2023 each contain only two missing values. The IncomeGroup variable has the largest amount of missing data which is 50 missing observations. These missing values are unlikely to substantially impact the overall analysis. Since the missing values appear to be associated with countries that lack an official income classification, the missingness is likely not completely at random.

# Checking for Duplicate Observations

> Add blockquote

In [ ]:
df_merged.duplicated().sum()
df_merged.info()

Using the duplicated() function, we discovered that there were no duplicated observations indicating that each row held a unique country observation. Therefore, no additional cleaning is needed.

### Graph based on Income Levels

In [ ]:
df_merged['Change'] = df_merged['2023'] - df_merged['2013']

# Group by income group and calculate mean change
df_plot = df_merged.groupby('IncomeGroup')['Change'].mean().reset_index()

# Define income group order
income_order = ['Low income', 'Lower middle income', 'Upper middle income', 'High income']

# Plot
plt.figure(figsize=(10, 6))
sns.barplot(data=df_plot, x='IncomeGroup', y='Change', order=income_order, color='Blue')

plt.title('Average Change in Electricity Access by Income Group (2013–2023)', fontsize=14)
plt.xlabel('Income Group')
plt.ylabel('Average Change in Electricity Access (%)')
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

"The graph reveals a clear inverse relationship between income level and electricity access growth over 2013–2023. Low income and lower middle income countries saw the greatest improvements, averaging approximately 14.7% and 14.9% respectively. There is a sharp drop at the upper middle income group

## Summary Statistics

In [ ]:
summary_stats = df_merged[['2013', '2023']].describe()

print(summary_stats)

## CountPlot

In [ ]:
plt.figure(figsize=(8,5))

sns.countplot(
    data=df_merged,
    x='IncomeGroup',
    order=['Low income',
           'Lower middle income',
           'Upper middle income',
           'High income']
)

plt.title('Number of Countries by Income Group')
plt.xlabel('Income Group')
plt.ylabel('Count')

plt.xticks(rotation=15)
plt.show()

## Histogram Multiplot

In [ ]:
fig, axes = plt.subplots(1,3, figsize=(15,5))

sns.histplot(df_merged['2013'], bins=20, ax=axes[0])
axes[0].set_title('Electricity Access (2013)')

sns.histplot(df_merged['2023'], bins=20, ax=axes[1])
axes[1].set_title('Electricity Access (2023)')

df_merged['Change'] = df_merged['2023'] - df_merged['2013']

sns.histplot(df_merged['Change'], bins=20, ax=axes[2])
axes[2].set_title('Change in Access (2013-2023)')

plt.tight_layout()
plt.show()

## Bivariate Analysis

In [ ]:
plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df_merged,
    x='2013',
    y='2023',
    hue='IncomeGroup'
)

plt.title('Electricity Access: 2013 vs 2023')
plt.xlabel('2013 Access (%)')
plt.ylabel('2023 Access (%)')

plt.show()

# Grouped Histogram Plot

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Violin plot: electricity access distribution by income group
sns.violinplot(data=df_merged, x='IncomeGroup', y='2023',
               hue='IncomeGroup', legend=False, ax=axes[0], palette='Set2',
               order=['Low income', 'Lower middle income', 'Upper middle income', 'High income'])
axes[0].set_title('Electricity Access by Income Group (2023)')
axes[0].set_xlabel('Income Group')
axes[0].set_ylabel('Electricity Access (%)')
axes[0].tick_params(axis='x', rotation=15)

# Count plot: number of countries per income group
sns.countplot(data=df_merged, x='IncomeGroup', hue='IncomeGroup', legend=False, ax=axes[1], palette='Set2',
              order=['Low income', 'Lower middle income', 'Upper middle income', 'High income'])
axes[1].set_title('Number of Countries per Income Group')
axes[1].set_xlabel('Income Group')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=15)

plt.suptitle('Electricity Access & Income Group Distribution', fontsize=13, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

 Violin Plot:
 Low income has the widest spread (nearly 0–100%), showing extreme inequality within the group — some low-income countries have near-full access, others almost none
Lower middle income is similarly wide but slightly top-heavy, suggesting more countries are progressing toward full access
Upper middle income is tightly clustered near 100% with a small tail — most are near saturation
High income is almost a flat line at 100% — virtually no variance

Count Plot:

High income has the most countries, but drives some of the most dramatic improvements
Sample size imbalance matters — averages from the bar chart earlier are based on very different group sizes

# Correlation Heat Map

In [ ]:
df_merged['Change'] = df_merged['2023'] - df_merged['2013']

numeric_cols = ['2013', '2023', 'Change']

correlations = df_merged[numeric_cols].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlations, annot=True, fmt=".2f", cmap="coolwarm", cbar=True,
            square=True, linewidths=0.5)
plt.title("Correlation Matrix: Electricity Access (2013, 2023, Change)", fontsize=13)
plt.tight_layout()
plt.show()

The -0.71 confirms the ceiling effect mathematically — starting low strongly predicts high growth
The +0.95 between 2013 and 2023 means relative country rankings are largely unchanged — rich stayed rich in access, poor stayed behind despite gains
The weaker -0.47 for 2023 vs Change shows the gap is slowly closing but inequality in access persists

# Scatter Multiplot

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.scatterplot(data=df_merged, x='2013', y='Change',
                hue='IncomeGroup', palette='Set2', alpha=0.5, ax=axes[0])
axes[0].set_title('Electricity Change vs 2013 Access')
axes[0].set_xlabel('Electricity Access 2013 (%)')
axes[0].set_ylabel('Change in Electricity Access (%)')

sns.scatterplot(data=df_merged, x='2023', y='Change',
                hue='IncomeGroup', palette='Set2', alpha=0.5, ax=axes[1])
axes[1].set_title('Electricity Change vs 2023 Access')
axes[1].set_xlabel('Electricity Access 2023 (%)')
axes[1].set_ylabel('Change in Electricity Access (%)')

plt.suptitle('Electricity Access Change vs 2013 & 2023', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

Strong negative trend in the left plot countries with low 2013 access (0–40%) saw the highest change (~20–49%), while countries near 100% in 2013 saw almost no change
The right plot mirrors this  by 2023, most high-change countries have "moved right" toward higher access, confirming real progress
Low & lower middle income (orange/blue dots) dominate the high-change, low-baseline zone
High income (green) clusters tightly at 100% with near-zero change ceiling effect confirmed
Outliers exist  a few lower middle income countries saw 40–49% gains,



> Add blockquote

# Methodology and Modeling
To formally quantify the relationships, we will use statistical models to examine whether income groups are associated with electrification rates in 2013 and 2023. To examine if income group is associated with electricity access, we use ordinary least squares linear regression. Linear regression will model the relationship between a response variable and explanatory variables by estimating coefficients that minimize the sum of squared residuals between the observed and predicted values. In this model, income group is treated as a categorical variable in order to estimate the average difference in electrification rates between the World Bank income classifications.
### Model Structure

**Model 1: 2013 Electrification**

$$
Y_i = \beta_0 + \beta_1(\text{IncomeGroup}_i) + \varepsilon_i
$$

where:

- $Y_i$ is the electrification rate for country $i$ in 2013,
- $\beta_0$ is the intercept,
- $\beta_1$ represents the effect of a country's income group,
- $\varepsilon_i$ is the random error term.

**Model 2: 2023 Electrification**

$$
Y_i = \beta_0 + \beta_1(\text{IncomeGroup}_i) + \varepsilon_i
$$

where:

- $Y_i$ is the electrification rate for country $i$ in 2023,
- $\beta_0$ is the intercept,
- $\beta_1$ represents the effect of a country's income group,
- $\varepsilon_i$ is the random error term.

In [ ]:
import statsmodels.formula.api as smf

# model 1
model1 = smf.ols(formula='elec_2013 ~ C(IncomeGroup)', data=df_model).fit()

# model 2
model2 = smf.ols(formula='elec_2023 ~ C(IncomeGroup)', data=df_model).fit()

### Model Comparison

In [ ]:
comparing_models = pd.DataFrame({
    "Model": ["2013", "2023"],
    "R²": [model1.rsquared, model2.rsquared],
    "Adj. R²": [model1.rsquared_adj, model2.rsquared_adj],
    "AIC": [model1.aic, model2.aic],
    "BIC": [model1.bic, model2.bic]
})

comparing_models

To compare the income group and access to electricity relationship, we looked at the coefficient of determination R^2 for both models. The 2013 model had an R^2 value of 0.706, while the 2023 model had an R^2 value of 0.646. This shows that income group is still a strong predictor of electricity access, but it shows that the effect has decreased slightly over time, which may be a result of improvements in electrification among lower-income countries.

## K-Means
For this project, we are required to use a method beyond the scope of the course. When researching additional methods, I found K-Means, an unsupervised machine learning technique that identitifies natureal groupings in data sets. The K-Means class can be found in the Scikit-learn library, and will group similar observations together, allowing our project to explore whether countries naturally form clusters based on their electrification rates in 2013 and 2023.

In [ ]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

#cluster variables
cluster_vars = df_model[['elec_2013', 'elec_2023']]

#standardizing the variables
cluster_scaled = StandardScaler().fit_transform(cluster_vars)

#KMeans
kmeans = KMeans(n_clusters=3, random_state=123, n_init=10)

df_model["Cluster"] = kmeans.fit_predict(cluster_scaled)

df_model.head()

### K-Means Scatterplot

In [ ]:
plt.figure(figsize=(8,6))

sns.scatterplot(data=df_model, x="elec_2013", y="elec_2023", hue="Cluster", palette="viridis")

plt.xlabel("Electrification Rate in 2013")
plt.ylabel("Electrification Rate in 2023")
plt.title("K-Means Clustering")
plt.legend(title="Cluster")

plt.show()

The K-Means clustering algorithm separated the countries into three main groups based on their electrification rates in 2013 and 2023. One group consists of countries that have almost complete access to electricity, another contains countries with moderate levels of access, and the last group is made up of countries with the lowest electrification rates. Overall, the graph shows that countries in all three clusters generally improved their access to electricity over the ten-year period. This supports the results from the regression models, which suggested that although lower-income countries still have lower electrification rates, many of them have made significant progress over time.

### Modeling Summary
Overall, the results from both the regression models and the K-Means clustering analysis show that income level has a strong relationship with access to electricity. The regression models produced relatively high R^2 values, with the 2013 model having an R^2 of 0.706 and the 2023 model having an R^2 of 0.646. This suggests that income group is still a strong predictor of electricity access, but its effect may have gotten slightly weaker over time as lower-income countries continue to improve.

The K-Means clustering analysis also supports these results. The algorithm naturally grouped countries into three clusters based on their electrification rates, with one group having almost complete access to electricity, another having moderate levels of access, and the last having the lowest access. Overall, both methods point to the same conclusion that income still plays a major role in electricity access around the world, but a lot of important progress in lower-income countries has been made between 2013 and 2023.

**Conclusion**

In our project, we explores the reltionship between country income levels and acess to elecrticity. We focused on the years 2013 and 2023 in the World Bank Dataset on Elecrtification to evaluate whether this relationship changed over a decade.



*   Our linear regression models revealed that a countrys income group is a statistically significant predictor of electricity acess. The 2013 model yielded an R^2 value of 0.706 and the 2023 model resulted in a R^2 of 0.646. This decrease suggusts that while income is an extremely influential facotr, the gap of electrification between income groups in gradualy narrowing. This tells us that lower income nations are making greated progess towards electrification over this ten year period.
*   The K - Meas analysis catoragized countires into three clusters, high, moderate and low acess. This highlighted that electrification remains uneven globaly. It also showed that countries across the three groups trended towards higher electrification rates over the decade which supports our regression findings that progess is being made.

The analysis confirms that universal energy access, a core pillar of the Sustainable Development Goals, remains heavily tied to economic development. Even though we found a correlation between lower income and reduced energy access, the data indicated a positive global trend. The progress observed in lower income countries between 2013 and 2023 provides evidence that policy and evelopment have greatly improved electricity access. Even though we are not at the SDG's goal of universal access, the weakened R^2 value of income electrification coorelation over the ten year period we studies suggusts that the energy divide is beginning to slowy be reduced.


To build upon the research we conducted in our project, our future models could also try to account for population density and urbanization. While this project measures the rate of electrification, it does not distinguish between the quality of access. A country with 90% access may still suffer from frequent brownouts or poor transmission quality compared to a country with 90% "acess that has a more modern grid. These factors could be god to look at for explaining more the the coorelation of energy acess. We could also extend our anaylsis to the present year, and also evaluate even earlier years to get a better understanding of the rate of improvement for electrification.